id: P006743
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:31.890254
source_metadata:
  id: bdr:W1KG6057
  title: བོད་ཀྱི་ཉེ་རབས་ལོ་རྒྱུས་ཏམྦུ་རའི་སྒྲ་དབྱངས
  author: ''
  volumes:
    debfcc2164674fc68ec9310f1010c449:
      image_group_id: I1KG6193
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
